apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: authservice
  namespace: family
  labels:
    app: authservice
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: authservice