apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: family
  labels:
    app: authservice
spec:
  type: ClusterIP
  ports:
   - port: 8080
     name: authservice
  selector:
   app: authservice