/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.kienast.authservice.rest.api;

import java.util.List;

import com.kienast.authservice.rest.api.model.ApplicationWithoutJwtModel;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@Validated
@Api(value = "appOfUser", description = "the appOfUser API")
public interface AppOfUserApi {

    @ApiOperation(value = "Get Apps of User", nickname = "getAppOfUser", notes = "", response = ApplicationWithoutJwtModel.class, responseContainer = "List", tags={ "app", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "App", response = ApplicationWithoutJwtModel.class, responseContainer = "List") })
    @RequestMapping(value = "/appOfUser/{username}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ApplicationWithoutJwtModel>> getAppOfUser(@ApiParam(value = "the name of the user",required=true) @PathVariable("username") String username);

}
